### PR TITLE
PSQLADM-243: Remove obsolete logrotate config

### PR DESCRIPTION
**Pull request by Sudokamikaze**
Package should only have one logrotate config

### CODE REVIEW

**Comment by Sudokamikaze** [comment]
@EvgeniyPatlan
Review please when you have time

**Comment by EvgeniyPatlan** [comment]
@Sudokamikaze please build packages and show output that logrotate is available after these changes

**Comment by Sudokamikaze** [comment]
@EvgeniyPatlan Here you go:
```
root@debian-10:/mnt/test/bin_deb# dpkg --listfiles proxysql2
/.
/etc
/etc/init.d
/etc/init.d/proxysql
/etc/logrotate.d
/etc/logrotate.d/proxysql-logrotate
/etc/proxysql-admin.cnf
/etc/proxysql.cnf
/lib
/lib/systemd
/lib/systemd/system
/lib/systemd/system/proxysql.service
/usr
/usr/bin
/usr/bin/proxysql
/usr/bin/proxysql-admin
/usr/bin/proxysql-status
/usr/bin/proxysql_galera_checker
/usr/bin/proxysql_galera_writer
/usr/share
/usr/share/doc
/usr/share/doc/proxysql2
/usr/share/doc/proxysql2/FAQ.md.gz
/usr/share/doc/proxysql2/LICENSE.gz
/usr/share/doc/proxysql2/README.md.gz
/usr/share/doc/proxysql2/changelog.Debian.gz
/usr/share/doc/proxysql2/changelog.gz
/usr/share/doc/proxysql2/compile_examples.txt
/usr/share/doc/proxysql2/copyright
/usr/share/doc/proxysql2/proxysql_notes.txt.gz
/usr/share/doc/proxysql2/requirements.txt
```

```
root@debian-10:/mnt/test/bin_deb# cat /etc/logrotate.d/proxysql-logrotate

/var/lib/proxysql/*.log {
        missingok
        daily
        notifempty
        compress
        create 0600 proxysql proxysql
        rotate 15
	postrotate
	. /etc/proxysql-admin.cnf
        /usr/bin/printf "%s\n" "[client]" "user=${PROXYSQL_USERNAME}"  "password=${PROXYSQL_PASSWORD}"  "host=${PROXYSQL_HOSTNAME}" "port=${PROXYSQL_PORT}"   | /usr/bin/mysql --defaults-file=/dev/stdin --protocol=tcp -Nse "PROXYSQL FLUSH LOGS"
        endscript
}
```

**Comment by vorsel** [comment]
Now there is a discrepancy between deb and rpm packages:
RPM packages contain logrotate file https://github.com/sysown/proxysql/blob/2.1.0/etc/logrotate.d/proxysql from sysown/proxysql repo:
etc/logrotate.d/proxysql-logrotate:
```
/var/lib/proxysql/proxysql.log {
    missingok
    notifempty
    copytruncate
}
```

And after this change deb packages will have https://github.com/percona/proxysql-admin-tool/blob/v2.0/proxysql-logrotate file from our percona/proxysql-admin-tool repo :
```
/var/lib/proxysql/*.log {
        missingok
        daily
        notifempty
        compress
        create 0600 proxysql proxysql
        rotate 15
	postrotate
	. /etc/proxysql-admin.cnf
        /usr/bin/printf "%s\n" "[client]" "user=${PROXYSQL_USERNAME}"  "password=${PROXYSQL_PASSWORD}"  "host=${PROXYSQL_HOSTNAME}" "port=${PROXYSQL_PORT}"   | /usr/bin/mysql --defaults-file=/dev/stdin --protocol=tcp -Nse "PROXYSQL FLUSH LOGS"
        endscript
}

```
We should decide which of them should be used in both cases.

**Comment by Sudokamikaze** [comment]
> Now there is a discrepancy between deb and rpm packages:
> RPM packages contain logrotate file https://github.com/sysown/proxysql/blob/2.1.0/etc/logrotate.d/proxysql from sysown/proxysql repo:
> etc/logrotate.d/proxysql-logrotate:
> 
> ```
> /var/lib/proxysql/proxysql.log {
>     missingok
>     notifempty
>     copytruncate
> }
> ```
> 
> And after this change deb packages will have https://github.com/percona/proxysql-admin-tool/blob/v2.0/proxysql-logrotate file from our percona/proxysql-admin-tool repo :
> 
> ```
> /var/lib/proxysql/*.log {
>         missingok
>         daily
>         notifempty
>         compress
>         create 0600 proxysql proxysql
>         rotate 15
> 	postrotate
> 	. /etc/proxysql-admin.cnf
>         /usr/bin/printf "%s\n" "[client]" "user=${PROXYSQL_USERNAME}"  "password=${PROXYSQL_PASSWORD}"  "host=${PROXYSQL_HOSTNAME}" "port=${PROXYSQL_PORT}"   | /usr/bin/mysql --defaults-file=/dev/stdin --protocol=tcp -Nse "PROXYSQL FLUSH LOGS"
>         endscript
> }
> ```
> 
> We should decide which of them should be used in both cases.

Thanks, we should provide only ours, fixed in RPM.

**Pull request merged**
